@startuml registro



' !theme amiga                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
' !theme aws-orange
' !theme black-knight                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
' !theme bluegray
' !theme blueprint                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
' !theme cerulean                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
' !theme cerulean-outline                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
' !theme crt-amber                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
' !theme crt-green                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
' !theme cyborg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
' !theme cyborg-outline                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
' !theme hacker                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
' !theme lightgray                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
!theme materia                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
' !theme materia-outline                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
' !theme metal                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
' !theme mimeograph                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
' !theme minty                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
' !theme plain                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
' !theme resume-light                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
' !theme sandstone                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
' !theme silver                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
' !theme sketchy                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
' !theme sketchy-outline                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
' !theme spacelab                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
' !theme superhero                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
' !theme superhero-outline                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
' !theme united 

skinparam sequenceMessageAlign center
actor Usuario
Usuario -> WelcomeSlidesPage: onRegisterClick()
create UserQuestPage
WelcomeSlidesPage -[#green]>> UserQuestPage: Redirige a la página

activate UserQResolverService
UserQResolverService -> ApiService: getLastUserQ()
note left: Se inicia \nautomáticamente
entity "API REST" as api 
activate ApiService
ApiService -> api: GET /api/questionnaire/last/user
api --> ApiService: Cuestionario JSON
ApiService --> UserQResolverService: Cuestionario JSON
deactivate ApiService
UserQResolverService --> UserQuestPage: Cuestionario JSON 
deactivate UserQResolverService

database LocalStorage 
Usuario -[#green]>> UserQuestPage: Rellena el cuestionario
Usuario->UserQuestPage: submit()
UserQuestPage -> LocalStorage: set('userA', this.userA)

@enduml
